type="2"
shType="list"
regionid="3"
section="40,41"
area="$_55$"
price="1000$_2500$"
houseage="$_15$"
prefer_road=["大學路","大德路","大義路","大觀路","學勤路","學府路","學成路","學林路"]
not_prefer_community=["日內瓦花園會館","樂活郡", "歐洲", "上善若水", "大英博物館", "巴黎花都", "北美館","世界公園", "隆恩", "維也納", "四季會館", "鼎禮","麗寶維也納花園","皇翔四季會館","麗寶維也納","WISH歐洲"]
