type="2"
shType="list"
regionid="3"
section="40,41"
area="$_55$"
price="1000$_2500$"
houseage="$_15$"
prefer_road=["大學路","大觀路","大德路","大義路","大雅路","大成路","學府路","學林路","學勤路","學成路"]
not_prefer_community=["達人生活","台北大大英維也納","麗寶世紀館","日內瓦花園會館","當代City","心六藝大廈","WISH歐洲","世界公園","樂活郡","北美館","上善若水","北大隆恩","麗寶維也納","麗寶維也納花園","麗寶維也納","上善若水","大英博物館","巴黎花都","愛在歐洲","世界公園","四季會館","皇翔四季會館","鼎禮","澄園","榮耀聖城"]
